import type { Mission } from "./types.ts";

// Social-setup focused; card text hints at the situation, not the exact trigger.
export const MISSION_DECK: Mission[] = [
  { id: "m001", title: "Set up a casual chat where numbers or a quick calculation come up.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m002", title: "Create a moment where a fact (place, date, name) feels relevant and you're both sure of your version.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m003", title: "Get into a conversation where wording and how you say things matter.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m004", title: "Weave a song or artist into the vibe, then let it reappear in the room later.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m005", title: "Steer things toward recommendations—shows, spots, food—and see who takes the bait.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m006", title: "Say something with quiet confidence that invites a gentle correction.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m007", title: "Start a thought and leave it hanging so someone else can complete it.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m008", title: "Drop a line that's just odd enough that someone has to double-take.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m009", title: "Create a moment where your posture or stance is contagious.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m010", title: "Lead the discussion to a point where agreement feels natural.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m011", title: "Set the scene for a small celebratory gesture—a win, a joke, a plan—and see who joins in.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m012", title: "Bring hunger or thirst into the mix and see who suggests fixing it together.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m013", title: "Get into a situation where using each other's names feels natural.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m014", title: "Share something personal enough that 'same' or 'me too' is a natural reply.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m015", title: "Create a moment where you're on a call and need a hand with a number.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m016", title: "Float an opinion and leave a beat for someone to align with it first.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m017", title: "Say something that almost demands a follow-up question.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m018", title: "Share something worth passing on and give them a reason to tell someone else.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m019", title: "Explain something simply and leave room for them to signal they've got it.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m020", title: "Create a situation where a knot—literal or figurative—is the obvious next step.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m021", title: "Set up a moment where you and they might say the same thing at the same time.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m022", title: "Let the vibe be good and leave the 'we should do this again' to someone else.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m023", title: "Introduce a small physical quirk and see who tries to help.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m024", title: "Ask a question that feels genuine and worth a considered answer.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m025", title: "Ask something they might not know and leave space for an honest answer.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m026", title: "Put yourself near someone new and create a natural opening for an intro.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m027", title: "Be present and warm; leave it to them to suggest doing it again.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m028", title: "Bring up a topic that leads naturally to 'let me show you'.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m029", title: "Create a reason they'd want to follow up with you later.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m030", title: "Do something small and useful and see if it gets acknowledged.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m031", title: "Casually bring direction or orientation into the conversation.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m032", title: "Create a moment where they're tempted to test something you've said about an object.", points: 4, difficulty: "legendary", tags: ["irl"] },
  { id: "m033", title: "Raise a topic that's easy to put off until later.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m034", title: "Wind down a thread in a way that invites a 'later' or 'next time'.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m035", title: "Mention something you'd want to remember or have sent—and leave the offer to them.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m036", title: "Create a natural pause that invites a deeper question.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m037", title: "Hint at time or tiredness and see who mirrors it.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m038", title: "Suggest the group might want a change of scene without proposing where.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m039", title: "Act a bit out of your depth and see who offers to help or stick around.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m040", title: "Put something in front of them—an idea or a thing—and leave room for a quick verdict.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m041", title: "Set up a small promise in front of them, then break it and see who reacts.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m042", title: "Create a reason they'd want to send you something after.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m043", title: "Speak just soft enough or in enough noise that listening requires a step closer.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m044", title: "Let something seem off—tired, emotional—and see who checks in.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m045", title: "Create a moment where a little reassurance would feel natural.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m046", title: "Set the mood for needing a laugh or a good joke.", points: 2, difficulty: "easy", tags: ["irl"] },
  { id: "m047", title: "Say something slightly unclear and see who asks you to say it again.", points: 1, difficulty: "easy", tags: ["irl"] },
  { id: "m048", title: "Let the gathering wind down and see who grabs the 'one last thing' moment.", points: 2, difficulty: "medium", tags: ["irl"] },
  { id: "m049", title: "Start a light 'confession' round and see who owns up to something small.", points: 3, difficulty: "hard", tags: ["irl"] },
  { id: "m050", title: "Be fully present and warm; leave any 'glad you're here' to them.", points: 4, difficulty: "legendary", tags: ["irl"] },
];
